# Generated by Django 3.2 on 2021-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='descriprion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
