# Generated by Django 3.2 on 2021-05-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_musician_descriprion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='descriprion',
            new_name='description',
        ),
    ]
